(in-package #:virality.examples)

;;; Prefabs

(virality.prefab:define-prefab "geometric-volumes" (:library examples)
  (("camera" :copy "/cameras/perspective"))
  (("plane" :copy "/mesh")
   (v/comp:transform :rotate/inc (q:orient :local (v3:one) pi)
                     :scale 6))
  (("cube" :copy "/mesh")
   (v/comp:transform :translate (v3:vec 0 30 0)
                     :rotate/inc (q:orient :local (v3:one) pi)
                     :scale 6)
   (v/comp:static-mesh :location '((:core :mesh) "cube.glb")))
  (("sphere" :copy "/mesh")
   (v/comp:transform :translate (v3:vec 0 -30 0)
                     :rotate/inc (q:orient :local (v3:one) pi)
                     :scale 6)
   (v/comp:static-mesh :location '((:core :mesh) "sphere.glb")))
  (("torus" :copy "/mesh")
   (v/comp:transform :translate (v3:vec 30 0 0)
                     :rotate/inc (q:orient :local (v3:one) pi)
                     :scale 6)
   (v/comp:static-mesh :location '((:core :mesh) "torus.glb")))
  (("cone" :copy "/mesh")
   (v/comp:transform :translate (v3:vec -30 0 0)
                     :rotate/inc (q:orient :local (v3:one) pi)
                     :scale 6)
   (v/comp:static-mesh :location '((:core :mesh) "cone.glb"))
   (v/comp:render :material 'virality.materials:unlit-texture-decal-bright)))

;;; Prefab descriptors

(virality.prefab:define-prefab-descriptor geometric-volumes ()
  ("geometric-volumes" virality.examples:examples))
