(in-package #:cl-user)

(defpackage #:virality.engine
  (:use #:cl)
  ;; definitions
  (:export
   #:define-annotation
   #:define-call-flow
   #:define-component
   #:define-geometry
   #:define-geometry-layout
   #:define-graph
   #:define-material
   #:define-material-profile
   #:define-options
   #:define-prefab
   #:define-resources
   #:define-texture
   #:define-texture-profile)
  ;;
  (:export
   #:attrs
   #:replace-action
   #:repeat-p
   #:action-step
   #:manager
   #:renderer
   #:on-action-insert
   #:on-action-finish
   #:on-action-update
   #:spawn-actor
   #:make-actor
   #:attach-component
   #:active-camera
   #:scene-tree
   #:frame-manager
   #:alpha
   #:using-material
   #:frame-count
   #:frame-time
   #:get-mouse-position
   #:destroy-after-time
   #:spawn-actor
   #:attach-components
   #:make-actor
   #:make-component
   #:input-enter-p
   #:frame-count
   #:input-data
   #:get-gamepad-analog
   #:option
   #:on-component-render
   #:on-component-attach
   #:on-component-detach
   #:on-component-destroy
   #:on-component-initialize
   #:on-component-update
   #:on-component-physics-update
   #:destroy
   #:display-id
   #:on-collision-enter
   #:on-collision-exit
   #:on-collision-continue
   #:meta
   #:total-time
   #:component-by-type
   #:mat-uniform-ref
   #:frame-time
   #:context
   #:id
   #:actor
   #:with-shared-storage))
